export default {
  bannerList: [
    {
      pictureUrl: require('../assets/image/home/bannerWrap@2x.png'),
    },
    {
      pictureUrl: require('../assets/image/home/bannerWrap2@2x.png'),
    },
  ],
  recommendList: [// 为你推荐图片数组
    {
      recommendUrl: require('../assets/image/home/recommendOne@2x.png'),
    },
    {
      recommendUrl: require('../assets/image/home/recommendTwo@2x.png'),
    },
  ],
  moduleSeparateList: [
    {
      'moduleId': 1,
      'moduleCode': 'PARTNER',
      'moduleName': '商业伙伴',
      'moduleIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/partner@2x.png',
      'roleId': 1,
      'roleCode': 'ADMIN',
      'roleName': '管理员',
      'functions': [
        {
          'functionId': 1,
          'functionCode': '110',
          'functionName': '客户创建',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/customerCreate@2x.png',
          'functionState': 'PartnerCreate',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 2,
          'functionCode': '120',
          'functionName': '客户维护',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/customerMaintain@2x.png',
          'functionState': 'PartnerList',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
      ],
    },
    {
      'moduleId': 2,
      'moduleCode': 'PROJECT',
      'moduleName': '项目申请',
      'moduleIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/project@2x.png',
      'roleId': 1,
      'roleCode': 'ADMIN',
      'roleName': '管理员',
      'functions': [
        {
          'functionId': 3,
          'functionCode': '210',
          'functionName': '融资试算',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/finaning-main@2x.png',
          'functionState': 'CalculationEnter',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 4,
          'functionCode': '100',
          'functionName': '租赁申请',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/applyCreate@2x.png',
          'functionState': 'PrjCreate',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 5,
          'functionCode': '130',
          'functionName': '申请维护',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/applyMaintain@2x.png',
          'functionState': 'PrjMaintenList',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
      ],
    },
    {
      'moduleId': 3,
      'moduleCode': 'CONTRACT',
      'moduleName': '合同模块',
      'moduleIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/contract@2x.png',
      'roleId': 1,
      'roleCode': 'ADMIN',
      'roleName': '管理员',
      'functions': [
        {
          'functionId': 6,
          'functionCode': '400',
          'functionName': '合同维护',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/contractMaintain@2x.png',
          'functionState': 'ContractMaintenList',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 7,
          'functionCode': '410',
          'functionName': '合同签约',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/contractSign@2x.png',
          'functionState': 'ContractSignList',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 44,
          'functionCode': '420',
          'functionName': '电子签章',
          'functionIcon': require('@/assets/home-manager/esign.jpg'),
          'functionState': 'Esign',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
      ],
    },
    {
      'moduleId': 4,
      'moduleCode': 'PERSONAL',
      'moduleName': '个人办公',
      'moduleIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/personWork@2x.png',
      'roleId': 1,
      'roleCode': 'ADMIN',
      'roleName': '管理员',
      'functions': [
        {
          'functionId': 8,
          'functionCode': '160',
          'functionName': '工作流',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/workflow@2x.png',
          'functionState': 'WorkflowList',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 9,
          'functionCode': '170',
          'functionName': 'OCR',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/ocr.png',
          'functionState': 'OcrIdentify',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        /* {
          'functionId': 43,
          'functionCode': '220',
          'functionName': 'Time',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/time@2x.png',
          'functionState': 'tab.time-task',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        }, */
        {
          'functionId': 45,
          'functionCode': '240',
          'functionName': '报表',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/chats@2x.png',
          'functionState': 'Reports',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 46,
          'functionCode': '250',
          'functionName': '启信宝',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/qixinbao.png',
          'functionState': 'QiXinBao',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 47,
          'functionCode': '260',
          'functionName': '风报',
          'functionIcon': require('@/assets/home-manager/riskTorm.jpg'),
          'functionState': 'RiskHome',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        /* {
          'functionId': 48,
          'functionCode': '270',
          'functionName': '小易',
          'functionIcon': require('@/assets/home-manager/robot.png'),
          'functionState': 'Robot',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        }, */
      ],
    },
    /* {
      'moduleId': 5,
      'moduleCode': 'PAYMENT',
      'moduleName': '付款管理',
      'moduleIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/payment@2x.png',
      'roleId': 1,
      'roleCode': 'ADMIN',
      'roleName': '管理员',
      'functions': [
        {
          'functionId': 10,
          'functionCode': '180',
          'functionName': '付款创建',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/payment-create@2x.png',
          'functionState': 'tab.payment-apply',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 11,
          'functionCode': '190',
          'functionName': '付款维护',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/payment-modify@2x.png',
          'functionState': 'tab.payment-modify',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
        {
          'functionId': 12,
          'functionCode': '200',
          'functionName': '付款支付',
          'functionIcon': 'http://hlsapp.hand-china.com/file/hel_dev/function/payment-pay@2x.png',
          'functionState': 'tab.payment-pay',
          'prodFlag': 'Y',
          'enableFlag': 'Y',
          'functionType': 'local',
          'target': null,
          'applicationFlag': 'N',
          'appCode': 'HLS_APP',
        },
      ],
    }, */
  ],
}
